In [1]:
import pandas as pd
import sqlite3

# Create Database 
conn = sqlite3.connect('../data/processed/job_market.db')

print("✅ Database connected successfully!")

✅ Database connected successfully!

In [2]:
# CSV data loading.............
df = pd.read_csv(r'C:\Users\user\Desktop\smart-job-market-intelligence\data\cleaned\ds_salaries_cleaned.csv')

# Save the data into database.........
df.to_sql('jobs', conn, if_exists='replace', index=False)

print("✅ Data loaded into database successfully!")
print(f"Total Rows: {len(df)}")

✅ Data loaded into database successfully!
Total Rows: 607

In [4]:
# First SQL Query
query = """
SELECT * FROM jobs LIMIT 5 """

result = pd.read_sql_query(query, conn)
result

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L
1,1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S
2,2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M
3,3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S
4,4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L

In [5]:
# Top 10 Highest Paying Job Titles
query = """
SELECT job_title, 
       ROUND(AVG(salary_in_usd), 2) AS avg_salary,
       COUNT(*) AS total_jobs
FROM jobs
GROUP BY job_title
ORDER BY avg_salary DESC
LIMIT 10
"""

result = pd.read_sql_query(query, conn)
result

                  job_title  avg_salary  total_jobs
0       Data Analytics Lead   405000.00           1
1   Principal Data Engineer   328333.33           3
2    Financial Data Analyst   275000.00           2
3  Principal Data Scientist   215242.43           7
4  Director of Data Science   195074.00           7
5            Data Architect   177873.91          11
6    Applied Data Scientist   175655.00           5
7        Analytics Engineer   175000.00           4
8           Data Specialist   165000.00           1
9              Head of Data   160162.60           5

In [6]:
# Experience Level wise Average Salary
query = """
SELECT experience_level,
       ROUND(AVG(salary_in_usd), 2) AS avg_salary,
       COUNT(*) AS total_jobs,
       ROUND(MIN(salary_in_usd), 2) AS min_salary,
       ROUND(MAX(salary_in_usd), 2) AS max_salary
FROM jobs
GROUP BY experience_level
ORDER BY avg_salary DESC
"""

result = pd.read_sql_query(query, conn)
result

  experience_level  avg_salary  total_jobs  min_salary  max_salary
0               EX   199392.04          26     69741.0    600000.0
1               SE   138617.29         280     18907.0    412000.0
2               MI    87996.06         213      2859.0    450000.0
3               EN    61643.32          88      4000.0    250000.0

In [7]:
# Company Size wise Salary Analysis
query = """
SELECT company_size,
       ROUND(AVG(salary_in_usd), 2) AS avg_salary,
       COUNT(*) AS total_jobs
FROM jobs
GROUP BY company_size
ORDER BY avg_salary DESC
"""

result = pd.read_sql_query(query, conn)
result

  company_size  avg_salary  total_jobs
0            L   119242.99         198
1            M   116905.47         326
2            S    77632.67          83

In [8]:
# Remote Work wise Salary Analysis
query = """
SELECT 
    CASE 
        WHEN remote_ratio = 0 THEN 'On-Site'
        WHEN remote_ratio = 50 THEN 'Hybrid'
        WHEN remote_ratio = 100 THEN 'Full Remote'
    END AS work_type,
    ROUND(AVG(salary_in_usd), 2) AS avg_salary,
    COUNT(*) AS total_jobs
FROM jobs
GROUP BY remote_ratio
ORDER BY avg_salary DESC
"""

result = pd.read_sql_query(query, conn)
result

     work_type  avg_salary  total_jobs
0  Full Remote   122457.45         381
1      On-Site   106354.62         127
2       Hybrid    80823.03          99

In [9]:
# Year wise Salary Trend
query = """
SELECT work_year,
       ROUND(AVG(salary_in_usd), 2) AS avg_salary,
       COUNT(*) AS total_jobs,
       ROUND(MIN(salary_in_usd), 2) AS min_salary,
       ROUND(MAX(salary_in_usd), 2) AS max_salary
FROM jobs
GROUP BY work_year
ORDER BY work_year ASC
"""

result = pd.read_sql_query(query, conn)
result

   work_year  avg_salary  total_jobs  min_salary  max_salary
0       2020    95813.00          72      5707.0    450000.0
1       2021    99853.79         217      2859.0    600000.0
2       2022   124522.01         318     10000.0    405000.0